[experiment]
name = ""
output_path = "."
images_path = ""
focus_path = ""
log_path = ""
roi_path = ""
protocol_path = ""

[reagents]

[image]
nz = 0

[expose]
n_exposures = 0

[focus]
routine = "partial_once" 

[stage]
tilt1 = 21500  
tilt2 = 21500  
tilt3 = 21500
z_init = 30000  


[optics]
power.red = 0
power.green = 0                                                  
filter.red = "home"
filter.green = "home"
exposure.Camera_558_687 = 1
exposure.Camera_610_740 = 1                                           

[pump]
flow_rate = 0                                                                   # uL/min
pause_time = 1                                                                  # Time to wait between aspirate and dispense in s
waste_flow_rate = 12000                                                         # uL/min

[logging]
version = 1
disable_existing_loggers = true

[logging.formatters.brief]
format = "%(asctime)s | %(levelname)s - %(message)s"
datefmt = "%m-%d %H:%M"

[logging.formatters.long]
format = "%(asctime)s | %(name)s - %(levelname)s - %(message)s"
datefmt = "%Y%m%d %H:%M:%S"

[logging.handlers.consoleHandler]
class = "logging.StreamHandler"
level = "INFO"
formatter = "brief"
stream = "ext://sys.stdout"

[logging.handlers.rotatingHandler]
class = "logging.handlers.TimedRotatingFileHandler"
level = "DEBUG"
formatter = "long"
filename = "~/.config/pyseq2500/logs/pyseq.log"
when = "midnight"
backupCount = 10

[logging.handlers.fileHandler]
class = "logging.FileHandler"
level = "DEBUG"
formatter = "long"
filename = ""

[logging.loggers.PySeq]
level = "DEBUG"
handlers = ["consoleHandler"]
propagate = false

[logging.root]
level = "WARNING"
handlers = ["consoleHandler"]