name: Test
Test:
  flowcells: ['A', 'B']
  PumpA: &pump
    volume:
      min_val: 100 #uL 
      max_val: 2000 #uL
    flow_rate:
      min_val: 100 #uL/min
      max_val: 10000 #uL/min
  PumpB: *pump
  ValveA: &reagent_valve
    n_ports: 24
    valid_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  ValveB: *reagent_valve
  XStage:
    spum: 1
    origin: 
      A: 100
      B: 200
    step: 100
    min_val: 0
    max_val: 50000
  YStage:
    spum: 1
    origin: 300
    step: 200
    min_val: -7000000
    max_val: 7000000
  TiltStage:
    spum: 100
    min_val: 0
    max_val: 30000
  ZStage:
    spum: 1
    step: 1
    min_val: 0
    max_val: 65000
  stage: 
    tilt1: &tilt
      min_val: 0
      max_val: 30000
    tilt2: *tilt
    tilt3: *tilt
  RedLaser: &red_laser
    min_val: 0
    max_val: 400
  GreenLaser: &green_laser
    min_val: 0
    max_val: 400 
  RedFilterWheel: &red_filter_wheel
    valid_list: {'home':0, 'open':1, '0.1':2, '1.0':3}
  GreenFilterWheel: &green_filter_wheel 
    valid_list: ['home':0, 'open':1, '0.1':2, '2.0':3]
  Camera_558_687:
    exposure: &camera_exposure
      min_val: 0.1
      max_val: 10
  Camera_610_740:
    exposure: *camera_exposure
  optics:
    laser:
      green: *green_laser
      red: *red_laser
    exposure: 
      Camera_558_687: *camera_exposure
      Camera_610_740: *camera_exposure
    filter: 
      green: *green_filter_wheel
      red: *red_filter_wheel