[experiment]
name = "TestExperiment"
#image_path = '.'
#focus_path = '.'
#roi_path = '.'
#protocol_path = None

[reagents]
PBS = 1
water = 2
formamide = 9
imager = {port=11, flow_rate=100}
imaging = {port=10, flow_rate=100, pause_time=10}

[image]
nz = 1

[expose]
n_exposures = 0

[focus]
routine = "partial_once" 

[stage]
tilt1 = 21500  
tilt2 = 21500  
tilt3 = 21500  


[optics]
power.red = 0
power.green = 0                                                  
filter.red = "home"
filter.green = "home"
exposure.Camera_558_687 = 1
exposure.Camera_610_740 = 1                                           

[pump]
flow_rate = 500                                                                 # uL/min
pause_time = 1                                                                  # Time to wait between aspirate and dispense in s
waste_flow_rate = 12000                                                         # uL/min