[roi1A]
flowcell = "A"
LLx = 14
LLy = 14
URx = 9
URy = 9
stage = {nz=1}

[roi1B]
flowcell = "B"
LLx = 16
LLy = 16
URx = 11
URy = 11
stage = {nz=1}

[A]
roi2 = {LLx=13, LLy=13, URx=8, URy=8, stage = {nz=1}}
roi3 = {LLx=17, LLy=17, URx=12, URy=12, stage = {nz=1}}

[B]
roi2 = {LLx=12, LLy=12, URx=7, URy=7, stage = {nz=1}}
roi3 = {LLx=18, LLy=18, URx=13, URy=13, stage = {nz=1}}