on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

name: Example

jobs:
  test:
    name: Test on python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: [windows-latest, windows-2022, windows-2019]
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v6
      with: 
        python-version: ${{ matrix.python-version }}
    - name: Test with python ${{ matrix.python-version }} and ${{ matrix.os }}
      run: uv run --frozen --dev pytest --cov=. 
